export const AUDIT_TAGS = {
    SERVER_REGISTERED: "SERVER_REGISTERED",
    SERVER_UNREGISTERED: "SERVER_UNREGISTERED",

    AUDIT_CHANNEL_SET: "AUDIT_CHANNEL_SET",

    PERMISSION_GRANTED: "PERMISSION_GRANTED",
    PERMISSION_REVOKED: "PERMISSION_REVOKED",
    PERMISSION_PRESET_APPLIED: "PERMISSION_PRESET_APPLIED",

    USER_VERIFIED: "USER_VERIFIED",
    USER_UPDATED: "USER_UPDATED",
    ROLE_BIND_CREATED: "ROLE_BIND_CREATED",
    ROLE_BIND_DELETED: "ROLE_BIND_DELETED",
    VERIFIED_ROLE_SET: "VERIFIED_ROLE_SET",

    TICKET_OPENED: "TICKET_OPENED",
    TICKET_CLOSED: "TICKET_CLOSED",
    TICKET_CATEGORY_SET: "TICKET_CATEGORY_SET",
    TICKET_TYPE_CREATED: "TICKET_TYPE_CREATED",
    TICKET_TYPE_REMOVED: "TICKET_TYPE_REMOVED",
    TICKET_PANEL_SET: "TICKET_PANEL_SET",
    TICKET_TRANSCRIPT: "TICKET_TRANSCRIPT",


    MODERATION_WARN: "MODERATION_WARN",
    MODERATION_MUTE: "MODERATION_MUTE",
    MODERATION_KICK: "MODERATION_KICK",
    MODERATION_BAN: "MODERATION_BAN",
    MODERATION_PURGE: "MODERATION_PURGE",

    STICKY_CREATED: "STICKY_CREATED",
    STICKY_DELETED: "STICKY_DELETED",
} as const;

export type AuditTag = typeof AUDIT_TAGS[keyof typeof AUDIT_TAGS];

export function formatAuditTag(tag: AuditTag) {
    return `[IRIS-AUDIT: ${tag}]`;
}